# Generated by Django 5.0.3 on 2024-04-12 06:59
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0003_auto_20240412_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, unique=True),
        ),
    ]
