# Generated by Django 5.0.3 on 2024-04-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_make_field_book_uuid_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        )
    ]
