# Generated by Django 5.0.3 on 2024-04-12 09:40
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0008_rename_uuid_to_id_not_affecting_db'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='book',
                    old_name='id',
                    new_name='uuid',
                ),
                migrations.AlterField(
                    model_name='book',
                    name='uuid',
                    field=models.UUIDField(default=uuid.uuid4,
                                           serialize=False, editable=False, primary_key=True),
                ),
            ],
        )
    ]
